[package]
name = "rnotify"
version = "0.1.0"
authors = ["Linus Probert <linus.probert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.0.0"
getopts = "0.2.21"
